spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output = true

# This configures Spring Boot to trust and use forwarded headers (like X-Forwarded-For) when behind a proxy or load balancer
server.forward-headers-strategy=framework 

server.port=8080
ADYEN_API_KEY=AQFEhmfxKY/KbBFGw0m/n3Q5qf3VaY9UCJ16aExb1nSuk2NFisZiGclvMiVgB/7xzYuhmDgJXNBK0HGpFlz+mPhRINz78zkQwV1bDb7kfNy1WIxIIkxgBw==-xKpZyI9abH3Cs/AxzwhHu3hvnIudbTUvPQ6xSqibIHk=-i1i@@Jkgwmg,7^ZM)}C
ADYEN_MERCHANT_ACCOUNT=AdyenPPImplementationTrainingTest2_CorebizBrazil_TEST
ADYEN_CLIENT_KEY=test_OGYDKKQXDJCWLONR4ETVTUB6C43RSG2U
ADYEN_HMAC_KEY=7BDBD1130F2D62A18E628D751F161A7224D00C1558410439EB5F59030B613083
